dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

script:
  - export HAMMER_HOME=$PWD
  - source sourceme.sh
  - cd src/test
  - if [[ $TRAVIS_PYTHON_VERSION != 3.3 && $TRAVIS_PYTHON_VERSION != 3.4 ]]; then pip install mypy && ./mypy_with_exclusions.sh; fi
  - ./unittests.sh
